import { NextResponse } from 'next/server';
import { triggerAutomation } from '@/lib/automation';
import { Transaction } from '@/lib/types';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    console.log('[DEBUG] Raw request body:', JSON.stringify(body));

    // Validate required fields
    if (!body.amount || !body.merchant || !body.category || !body.date) {
      return NextResponse.json(
        { error: 'Missing required fields: amount, merchant, category, date' },
        { status: 400 }
      );
    }

    // Create transaction object - use ID from request body (generated by UI)
    const transaction: Transaction = {
      id: body.id || Date.now(), // Use provided ID, fallback to Date.now()
      amount: body.amount,
      merchant: body.merchant,
      category: body.category,
      date: body.date,
      verified: body.verified || false,
    };

    // Trigger the automation workflow
    await triggerAutomation(transaction);

    return NextResponse.json(
      {
        success: true,
        message: 'Transaction created and automation triggered',
        transaction,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error('Error in add-transaction route:', error);
    return NextResponse.json(
      { error: 'Failed to process transaction', stack: (error as any).stack },
      { status: 500 }
    );
  }
}
